### PR TITLE
Validate folders with the definition domain and type

### PR DESCRIPTION
**Pull request by apoloa**
### Relevant information

Added validation for the folder names using the type and domain of the type.
Audit dependencies to fix critical issues. 

### Checklist

* [ ] I've read the guidelines and understand the acceptance criteria.
* [ ] The value of the attribute marked as `identifier` will be unique and valid. 
* [ ] I've confirmed that my entity type wasn't already defined. If it is I'm providing an
 explanation above.

### CODE REVIEW

**Review by IreneMLC — APPROVED** [review]
Thank you!

**Comment by IreneMLC** [comment]
When the CLA doesn't ❌  you I'll merge this

**Comment by srvaroa** [comment]
@apoloa ping (CLA)

**Review by naxhh — APPROVED** [review]
nice!

**Pull request merged**
