### PR TITLE
Correcting errors after testing

### PR DESCRIPTION
**Pull request by AlbertoGoYu**
Detected and corrected couple of errors with NLB Target groups after testing the merged PR
 
- Golden Metrics corrected
- Golden Tags corrected

### CODE REVIEW

**Comment by AlbertoGoYu** [comment]
Sorry I used my GHE user in one of those branches and now I can't see how to sing the license. Could you please disregard this PR while I figure out how to rever those changes and do another PR again.

**Comment by IreneMLC** [comment]
Been there @AlbertoGoYu, I had to add my GHE email to my account here and then I was able to sign it (just to give you a quick alternative).

**Comment by naxhh** [comment]
Also it would be better for us to have smaller Pr's with just 2-5 types. This big PR's are hard to validate

**Comment by naxhh** [comment]
If you are going to do another PR i'm closing this one. feel free to reopen if required

**Pull request closed without merging**
